### ISSUE TITLE
add formatting to grid groupField

### ISSUE THREAD

**Issue by ghost** [tonytomov/jqGrid#100]
jqGrid version 3.8.1. 
jQuery version 1.4.3

What steps will reproduce the problem?
1. if one puts a formatter on the group field of grid , the same should get applied to the group title.
1. the grouping seems to be happening before the formatter is applied.
   and that makes sense. But atleast once the grouping is done, the group text should be the formatted version.

What is the expected output? What do you see instead?
grouptext which currently can be of the form {0} - {1}
Here {0} should be the formatted version (if formatter is applied on group field)
Unformatted version of group field is currently seen.

**Comment by jaimestuardo** [comment]
I am facng the same problem. Any workaround on thie? I have a complex object list that is showing in the grid, so that, I had to place a formatter for each column. 

I need to group for one column, but the format is not applied.

The result. Only 1 group appears at the top of the list and with blank text.

Please see the attached image. I need to gropup by column called "Tipo".

Any help will be appreciated. Thanks.

![image](https://user-images.githubusercontent.com/9195659/34313677-9f774c08-e74b-11e7-9339-7f5ed8023668.png)
