### ISSUE TITLE
Non-standard language names for Chinese and Taiwanese

### ISSUE THREAD

**Issue by jdetaeye** [tonytomov/jqGrid#544]
Jqgrid uses a non-standard names for these locales:
   - "CN" should be "ZH-CN"
   - "TW" should be "ZH-TW"

Jquery-UI and Django both use the indicated standard name.

The deviating names in jqgrid make it harder to correctly integrate it in a multi-lingual application - additional code is required to handle the jqgrid names, or one needs to rename the jqgrid files manually.

**Comment by tonytomov** [comment]
Hello,

I think we need to use one standard. The problem is that different standards does not meet the all the user requirement. 
I agree with this: http://bodeuxinternational.com/locales-and-lang-codes/ 
We can use two letter code and if it there is a need we can use 4 letter described like in the link above.
