### ISSUE TITLE
Resizing columns in RTL mode in Chrome 

### ISSUE THREAD

**Issue by VahidN** [tonytomov/jqGrid#612]
Hello,
Resizing columns in RTL mode in Chrome doesn't work correctly. here is the screenshot of the issue.

![Image of the issue](http://www.dotnettips.info/file/image?name=Capture-797c031dc5354856a8511a89481a30c6.PNG)
As you can see, headers width and columns width are not synchronized in chrome.
It works fine in IE and Firefox.

**Comment by tonytomov** [comment]
Hello,

Does the problem happen in FireFox or IE?
As far as I know Chrome does not support fully RTL or I'm wrong.

**Comment by OlegKi** [comment]
Hello Tony,

I suppose that Chrome just have *another* RTL implementation. The described problem exist in different versions of Chrome. I changed the `pagging-left` value of `hbox` in my fork of jqGrid and now all works correctly (see [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/groupingRtl1.htm) for example). So the problem do can be solved inside of jqGrid code independent on whether the problem is a bug in Chrome or not. 

Best regards
Oleg
