### ISSUE TITLE
Hi, I want to know the jqgird's license?

### ISSUE THREAD

**Issue by hjzheng** [tonytomov/jqGrid#646]
Can you tell me the project's license?

**Comment by Niggler** [comment]
@hjzheng @meh-uk This may have been true at one point, but it is decided not free now.  I think the commit https://github.com/tonytomov/jqGrid/commit/1b2cb55c93ee8b279f15a3faf5a2f82a98da3b4c shows the change

@tonytomov it appears that quite a few people have contributed code.  Did you get their approval before changing the license?  I don't see a CLA anywhere, and by default the contributed still belongs to them.

**Comment by slang25** [comment]
@tonytomov can you comment? Did you reverse the contributions of the 60 odd other contributors or get their permission?

**Comment by meh-uk** [comment]
@slang25 what @tonytomov has done may well be legal under the MIT licence as we could all use jqGrid commercially. However it is quite clear Tony hasn't consulted a lawyer before or since making these changes which is exceedingly foolish.

**Comment by slang25** [comment]
Thanks @meh-uk, so to be clear, the code up to and including 4.7 was under MIT/GPL2 and therefore we can always use that and your community fork in a commercial product.

But in terms of this repo, it's ok to remove the existing licence that the contributors made their changes under, and apply a new licence?

I am more interested that anything else, I appreciate all the work @tonytomov, @OlegKi, @flack, @bouks and yourself have done and continue to do.

**Comment by Niggler** [comment]
@slang25 my understanding is that the copyright of all contributed code is still retained by the original authors, and that it would take unanimous consent to change.

VLC had this problem recently, when they relicensed the VLC engine to LGPL.  Noted at the time:

> All the developers have agreed to the relicensing, but a famous one, who refused to answer. His code was therefore rewritten.

For more information, here is the press release: http://www.videolan.org/press/lgpl-libvlc.html 

In absence of a clear CLA, **every contributor** has to agree to the change. That's why I raised the question -- I would be surprised if every contributor agreed to the new terms.

**Comment by flack** [comment]
@Niggler yes, we've raised the same question in the commit you referenced above. there was some discussion about it, but tony deleted it since. I think his position is just to ignore all criticism and to hope that most people won't notice..

**Comment by Niggler** [comment]
@flack at the end of the day I feel bad for you and other contributors who spent hours and days and weeks working with the project.  

I hope that you see @tonytomov as a bad actor rather than lowering your view of the entire open source community.  Most of us sincerely appreciate the hard work of other people and aren't stupid enough to pull this stunt without getting prior approval.

**Comment by meh-uk** [comment]
I'm not turned off all open source. I think that's life.

**Comment by mirik123** [comment]
The 4.7.0 version is MIT/GPL
The 4.7.1+ versions are free only for nonprofit projects (like ExtJS).
