### ISSUE TITLE
[Suggestion] Responsive top|bottom pager buttons

### ISSUE THREAD

**Issue by demonslord** [tonytomov/jqGrid#678]
Hi Tony,

**Problem/Issue** :

When you have responsive grid and many buttons on pager, they are overlapping on small size.

**Suggestion** :
- Change the DOM structure, < table > to < ul > for better control and less html
- Implement the responsive menu for pager buttons, I mean something like [this](http://www.meanthemes.com/plugins/meanmenu/) , on small resize convert to one button/icon and `onclick` show the popup menu with buttons.
- It will be very useful when, we have responsive grid in small container/area.

Best Regards.

**Comment by OlegKi** [comment]
Hi @demonslord ,

I made very close changes of the structure of navigator in [my fork of jqGrid](https://github.com/OlegKi/jqGrid). I use just `<div>` elements instead of `<td>`. As the result one have the same effect like you describe. Tony could implement close changes in his repository it he'll find it helpful.

You can see the results of new navigator structure on the demos at the end of [the page](https://github.com/OlegKi/jqGrid) ([icons](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons0.htm), [icons with text](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons1.htm), [icons with text under icons](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons2.htm) and the same demos, but using vector-fonts: [icons](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons0-fa4.htm), [icons with text](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons1-fa4.htm), [icons with text under icons](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons2-fa4.htm)). By the way you can resize grids in all demos horizontally to see how the navigator bar will be changed on changing the width of the grid.

Best regards
Oleg

**Comment by demonslord** [comment]
@OlegKi 

Thank you for the answer.

>By the way you can resize grids in all demos horizontally to see how the navigator bar will be changed on changing the width of the grid.

But your grid is not responsive, it should resize on window resize.

Best Regards,
Alexander

**Comment by tonytomov** [comment]
Hello Alexnader,

Thank you very much for the recommendations. 
The first is recommended many time and I think I will switch to it. The second must be.
Currenty I prepare a new release and I will see if I will have chance to do this.
In all cases I will let you know.

Kind Regards,
Tony

**Comment by demonslord** [comment]
@tonytomov 

Thank you.

>The second must be.

It will be very nice and practical "add-on" to the grid ;)

Best Regards.
