### ISSUE TITLE
Column Chooser height option does not appear to be working

### ISSUE THREAD

**Issue by dizzy0ny** [tonytomov/jqGrid#697]
In the code below, regardless of what i set height to, the column chooser opens up at the same height.  I have a large number of columns available to choose from on my grid (~50).

        .jqGrid("navGrid", "#pager", { add: false, edit: false, del: false }, {}, {}, {}, {}, {}, {},
                {multipleSearch: true, multipleGroup: true, closeOnEscape: true, showQuery: true, closeAfterSearch: true})
        .jqGrid("navButtonAdd", "#pager", {
            caption: "",
            buttonicon: "ui-icon-calculator",
            title: "Choose Columns",
            onClickButton: function () {
                $(this).jqGrid("columnChooser", { height: 100 });
            }
        })

I am using this with jquery 1.11.2 and jquery-ui 1.11.4.

**Comment by tonytomov** [comment]
Hello,

I confirm the problem. There is another bug related to select all, remove all links. I hope we will fix this ASAP.

**Comment by tonytomov** [comment]
Hello,

In order to solve the problem you will need to set the dialog_opts  like this

```
$(this).jqGrid('columnChooser', { dialog_opts :{ height:300} ,...});
```

Kind Regards

**Comment by Abhishek2792** [comment]
Hello,
$(this).jqGrid('columnChooser', { dialog_opts :{ height:300} ,...});  only sets the dialog box height. In case of many columns, bottom part of scrollbar is hidden and some items from multi select list are not visible since it's height is not adjusted with respect to dialog box. Observed that manual resizing of dialog sets the proper height for multi select list.

**Comment by luytk12** [comment]
Hello,
I have the same issue as Abhishek2792. Scrollbars are not visible after setting dialog  height.
