### ISSUE TITLE
frozen-bdiv for data columns remains empty works for header row only

### ISSUE THREAD

**Issue by d691maurya** [tonytomov/jqGrid#734]
![desctop screenshot](https://cloud.githubusercontent.com/assets/12238760/10723014/735ee090-7bdc-11e5-8eac-9d0f32b59493.png)

As you can see in above screenshot frozen-bdiv for data columns remains empty works for header row only.

**Comment by tonytomov** [comment]
Hello,

Please, prepare a example in order to see the problem and help to resolve the problem
Thank you.

Kind Regards,
Tony

**Comment by d691maurya** [comment]
Here's the example

https://jsfiddle.net/9s1eLhab/3/

Thanks,
Diwakar

**Comment by tonytomov** [comment]
Hello,

The example can not be run. Moreover you use the old 4.5.2 version. Current version is 5.0.1.
PLease prepare a example an include non minified version of jqGrid

**Comment by d691maurya** [comment]
Hello Tony,

https://jsfiddle.net/9s1eLhab/7/

Here is the working example again. jqgrid.pivot.js is not available on any cdn so I had to put it on google drive and the link was expired that's why example was not working.

Also because time constraints it is not possiblt to upgrade jqgrid for now. So it will help if you can provide a fix for this.

Thanks,
Diwakar

**Comment by OlegKi** [comment]
@d691maurya : Sorry, Diwakar, but you use `jqPivot` from [free jqGrid](https://github.com/free-jqgrid/jqGrid) (see [here](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.pivot.js)) in combination with very old jqGrid version 4.5.2, which have some bugs in frozen columns, which are fixed in more recent versions. It's unclear for me, which relation have the code to Guriddo jqGrid JS with the current version 5.0.1. 

It has no sense in reporting of bugs in 4.5.2, which are already fixed. Moreover you should clear decide, which fork of jqGrid you use. In any way you should *never mix modules from one version with other modules from another versions*. Such way will be never supported!

**Comment by d691maurya** [comment]
Hello Oleg,

Thanks for the clarification. I was not aware of two different forks of jqgrid. I will try to upgrade to latest version of jqgrid.

Thanks,
Diwakar
