### ISSUE TITLE
GridUnload in IE8

### ISSUE THREAD

**Issue by Juliete** [tonytomov/jqGrid#735]
When call to the function $.jgrid.gridUnload(id) a exception ocurs saying that an object has hasOwnProperty undefined.
I attach a screenshot 
![error](https://cloud.githubusercontent.com/assets/9534060/10738406/9a1827ce-7c17-11e5-92e9-dd2139dee087.jpg)

**Comment by tonytomov** [comment]
Hello,

Thank you for reporting this. Instead that we have drop the support for IE8 (as jQuery do) we will try to fix this problem.

For this purpose can you please include the non minified version in order to see where eventally is the problem

In order to make this quick it is highly recommended to prepare a simple example which demonstrates the problem.

Kind Regards,
Tony

**Comment by Krokador** [comment]
Hello, 
We are having the same issue. On line 851 of the jqGrid.js file we have
`l = removevents.length;
		for(i = 0; i < l; i++) {
			**if($t.hasOwnProperty(removevents[i])) {**
				$t[removevents[i]] = null;
				delete($t[removevents[i]]);
			}
		}`

if I change that line for 
`if(Object.prototype.hasOwnProperty.call( $t, removevents[i])) {`

then IE8 works just fine. There might be more lines that could be problematic around that function which our settings don't stumble on, though.

**Comment by tonytomov** [comment]
Hello,

obj.hasOwnProperty is not supported in IE8 and below.
https://msdn.microsoft.com/en-us/library/328kyd6z%28v=vs.94%29.aspx

There is no problem to change the code in Grid using your fix, but I ask you - what you will do with other libs if they use the same obj.hasOwnProperty?

The better is maybe this
```
if (!Object.prototype.hasOwnProperty) {
    Object.prototype.hasOwnProperty = function(prop) {
        var proto = this.__proto__ || this.constructor.prototype;
        return (prop in this) && (!(prop in proto) || proto[prop] !== this[prop]);
    };
}
```

There are a lot of posts and solutions of this problem. You just need to find them.

The code above is taken from stackoverflow:  http://stackoverflow.com/questions/17150396/benefit-of-using-object-hasownproperty-vs-testing-if-property-is-undefined

**Comment by Krokador** [comment]
Just wanted to share what the fix ultimately ended up being. IE8 is rather stupid and the above code did not work, because for some reason Object.prototype.hasOwnProperty is actually defined in IE8, but does not carry over to DOM elements. 

The solution for this particular error ended up being:

`
	if (!document.getElementsByTagName("body")[0].hasOwnProperty)
	{
		HTMLTableElement.prototype.hasOwnProperty = function (prop)
		{
			var proto = this.__proto__ || this.constructor.prototype;
			return (prop in this) && (!(prop in proto) || proto[prop] !== this[prop]);
		};
	}
`

Somewhere at the end of the page or in a jQuery onready (note: any DOM element would work, as long as it is not null). This particular fix only works if the DOM element is a table like the above case. Other HTML elements might have to be added in different instances.

**Comment by tonytomov** [comment]
Hello,

Thank you for sharing. 
Instead that we have drop the support for IE8 this is useful information for all us.

**Comment by tonytomov** [comment]
Hello,

Since @Krokador  does not close the issue, I will close it. In case of problem, please consider reopen.
