### ISSUE TITLE
Encode and decode additional characters to prevent XSS

### ISSUE THREAD

**Issue by Lukenickerson** [tonytomov/jqGrid#742]
[OWASP XSS Prevention rule 1](https://www.owasp.org/index.php/XSS_%28Cross_Site_Scripting%29_Prevention_Cheat_Sheet#RULE_.231_-_HTML_Escape_Before_Inserting_Untrusted_Data_into_HTML_Element_Content) suggests that six characters be escaped, whereas jqGrid only encodes/decodes four in `htmlEncode` and `htmlDecode`. 

I would suggest also escaping single-quotes and forward-slashes using something like `.replace(/'/g, "&#x27;").replace(/\//g, "&#x2F;")`.

**Comment by tonytomov** [comment]
Hello,

Sorry for the late answer. 
I'm not sure if adding this is fine for now - I think that some existing user applications will break.

In order to use these you may can redefine your htmlEncode and htmlDecode after loading the jqGrid files
````
	$jgrid.htmlDecode = function(value){
		if(value && (value==='&nbsp;' || value==='&#160;' || (value.length===1 && value.charCodeAt(0)===160))) { return "";}
		return !value ? value : String(value).replace(/&gt;/g, ">").replace(/&lt;/g, "<").replace(/&quot;/g, '"').replace(/&amp;/g, "&").replace(/'/g, "&#x27;").replace(/\//g, "&#x2F;");
````

The appropriate for htmlDecode
Thank you mark this.

Kind Regards,
Tony
