### ISSUE TITLE
Filter's is in \ contains functionality not working

### ISSUE THREAD

**Issue by saadrizvi** [tonytomov/jqGrid#743]
When trying to use the search functionality's contains or is in feature, the query does not provide the accurate results.

For example, if you look at this example found on your own site:
http://www.guriddo.net/demo/guriddojs/searching/dialog_multiple/index.html

If you try to do a search where Order ID is in 10249 the result is as expected. 
If you try to do a search where any + Order ID is in 10248 + Order ID is in 10249 the result is as expected. 
However, if you try to do a search where Order ID is in 10248,10249 the result is inaccurate (empty).

This can also be found throughout examples:  
http://www.trirand.com/blog/jqgrid/jqgrid.html
(Searching -> Show query in search) search on Inv No is in 8, 9, 10 --> results in nothing displayed.

Even this random JS Fiddle I found, has the same issue with Inv No. http://jsfiddle.net/IrvinDominin/zdACB/

**Comment by tonytomov** [comment]
Hello,

Thank you for investigation. 

When the searching is performed in server, (the first examples) then the search depend on the logic in the server. The reason that the query like WHERE OrderID is in (10248,10249) does not work is the fact that at the PHP server we use a prepared queries in order to prevent SQL injection.

As you know in case of prepared queries passing parameter with comma like the above is rejected due to security reasons.

As for the local data searching (the least jsfiddle example) we do not support IN clause, but we will see what we can do to extend this functionality.

Kind Regards,
Tony
