### ISSUE TITLE
getInd does not take paging into consideration

### ISSUE THREAD

**Issue by oliverjm** [tonytomov/jqGrid#746]
If you have a grid with multiple pages, getInd will always return the index relative to the available rows for the current grid page.  If you're writing code to get the selected data for the current row index this will never work as the param object data returns the data for all rows in the grid based on a correct row index. 

EX:  getInd of selected row 6 in grid with 11 rows and page size set to 5 will get the value of 1.  Using this value to get the selected data from the data param will not return the data you are expecting even if you use a zero based index like getInd - 1.

**Comment by tonytomov** [comment]
Hello,

Yes this is true and the definition of the function is like described by you. Se the definition - http://www.trirand.com/jqgridwiki/doku.php?id=wiki:methods&s[]=getind we speak about table and not data.
You request have sense only if the datatype is local, but in this case you can get easy the index using the _index grid parameter. 

In a server side data this does not have sense moreover will get wrong result since the rows vary recent.

**Comment by oliverjm** [comment]
Yep, that's what I'm using but I didn't see it in the documentation.  Found
it through a debugging session looking at the available grid param objects
for a particular grid.  Thanks.

Josh

**Comment by tonytomov** [comment]
Hello,

I will close the issue
