### ISSUE TITLE
Decoupling from JqueryUI

### ISSUE THREAD

**Issue by MichaelZaporozhets** [tonytomov/jqGrid#799]
JqueryUI is a massive pain and should realistically never be used in any kind of serious javascript visualisation framework. This jqGrid does so many fantastic things so well and I feel that it's time to remove the ugliest dependency for this library (this is also me raising my hand, willing to help).

**Comment by tonytomov** [comment]
Hello Michael,

This is too bold proposal!

I understand your point, but believe me I can't do this currently. There are a lot of reasons including historical one - I can't forget from where jqGrid begin.

Now we have a Bootstrap and we have changed jqGrid code so that it can be used with any CSS frame work.

Supporting of more CSS frameworks (including jQuery UI) is a plus.

Best Regards,
Tony

**Comment by tonytomov** [comment]
Will close the recommendation.
