### ISSUE TITLE
Refreshing Grid using Local data

### ISSUE THREAD

**Issue by joeJazdzewski** [tonytomov/jqGrid#820]
When I try refreshing my grid with the code below the page is not set to page 2 but instead is set to page 1. I am using "local" as my datatype

`$("#Grid").clearGridData();`
` $("#Grid").setGridParam({data:newData}).trigger("reloadGrid", [{page: 2}]);`

When just using the second line, if the number of rows in newData is less than the number of rows in jqGrid's data then I get a combination of new and old data.

[Example](https://keen-crystal.hyperdev.space/)

**Comment by joeJazdzewski** [comment]
I was able to find a work around by using the following code

`var numRows = $("#Grid").getGridParam("numRows");`
`$("#Grid").setGridParam({data: newData, lastpage:(newData / numRows) + 1}, true);`
`$("#Grid").setGridParam({data: newData}).trigger("reloadGrid", [{page: 2}]);`

**Comment by tonytomov** [comment]
Hello,

This is not a bug, but a way od calling a certain command in certain sequence.
The "problem" is in clearGridData. When you call this command all pager parameters are set to its initial state. After this you call setGridParam with the new data and try to reload the grid with page : 2. When you reload the grid check for the lastpage, which is set to 0 from the previous command, but the new data is not yet loaded in order to calculate the new lastpage (Catch 22)

In order this to work the correct is to set the page:2 in setGridParam:

````
$("#Grid").clearGridData();
$("#Grid").setGridParam({data:newData, page:2}).trigger("reloadGrid");
````


Regards

**Comment by joeJazdzewski** [comment]
Thanks
