### ISSUE TITLE
Pager width problem

### ISSUE THREAD

**Issue by xovel** [tonytomov/jqGrid#832]
A table's width is not enough, the pagination will be clipped, the `select` element maybe get out of our sight.

Hope there is an option to set the pager's width.

![](http://ww4.sinaimg.cn/large/79be2309gw1faykbzz5khj20d70aejt1.jpg)

**Comment by tonytomov** [comment]
Hello,

Could you please post a test case where we have this problem?
It is important to have full test case and not only partial one.

Kind Regards,
Tony

**Comment by xovel** [comment]
I just set the middle pager's width to solve this problem already.
******
BUT, it has another problem: the info of pagination has been out of view.

I try to display my code to `jsfiddle`, but failed to load the dependencies, so I upload a sample to one my own github repo and use `htmlpreview.js` to display it:

[DEMO](http://htmlpreview.github.io/?https://github.com/xovel/diary/blob/master/vendors/issue/jqgrid-issue-832.html)

Ref: [Guriddo jqGrid Bootstrap Demo](http://www.guriddo.net/demo/bootstrap/)

**Comment by tonytomov** [comment]
Hello,

You need to understand that it is not possible to display all the page info when the table is too small.
There is no option to set another width of the pager. Consider a pager as a part of the grid. Setting as separate div just stay for historical purposes, so that this will not brake the existing code of older versions.

You can control the text using the language file or set **recordtext** grid parameter to meet your grid width

Regards

**Comment by xovel** [comment]
Well, thanks a lot for your reply. 😄
