### ISSUE TITLE
Gets the data of the large table of the edit state

### ISSUE THREAD

**Issue by jinjim** [tonytomov/jqGrid#838]
I now have a large table that needs to be submitted to the background in an edit state. My way is to get the rowid first, then saveRow according to the rowid, and finally get the data, but I find that the speed is particularly slow, at least 8 minutes , So would like to ask under what is a good way?

**Comment by tonytomov** [comment]
Hello,

In a big table data saving this it is not a good idea, ince if you have 100 editable records, then 100 ajax request will be made. It is much easier  to go in local  data and save the data  array to the server.
Suppose you use similar to this example: http://www.guriddo.net/demo/guriddojs/edit_add_delete/inline_batch/index.html

When the grid is loaded you set the grid parameter **loadonce** to true  in order to have the local data array. Go in edit mode and set the editurl to '**clientArray**' - this way when you push the save button your data will be saved locally and after that you can get the **data** array and post it to the server.

Regards

**Comment by jinjim** [comment]
I appreciate for you help.but， there is another problem.when i set loadonce to be true  and editurl to be  'clientArray',i also did some thing else    ($("#EditList").jqGrid().setGridParam({datatype:'json'}).trigger('reloadGrid');). but， I suddenly found that the total number of query results is not correct. the total number turned to be  20(the default pageSize), and could not query by pageSize   dynamically.

**Comment by tonytomov** [comment]
Hello,

Maybe you have a error in your command. Try:

```js
...
$("EditList").jqGrid('setGridParam',{datatype:'json'}).trigger('reloadGrid');
...
```

Regards

**Comment by jinjim** [comment]
tks,I tracked js code and i found the performance problem come from saveRow method. and  you give me the method can not meet my needs.so I would like to ask how to speed up the method of save data to localdata?

**Comment by tonytomov** [comment]
Hello,

Since is difficult to understand what you mean, could you please prepare a example in order to see what you try to achieve. You can use https://jsfiddle.net/ for this purpose 

Regards

**Comment by tonytomov** [comment]
I will close the issue. Please reopen if you find difficulties.
