### ISSUE TITLE
.NET demo

### ISSUE THREAD

**Issue by papyr** [tonytomov/jqGrid#980]
Hello any chance we can use this in a ASP Core .NET application many more developers could use it.

Use case a with a master-detail sample would be very helpful.

**Comment by tonytomov** [comment]
Hello,

There is jqGrid for ASP Core .NET, but it seems the developers stop working on it. 
Here is the site: http://trirand.net/default.aspx ,
Before do anything, please contact them in order to be sure that you will get the appropriate support.
The version they supported is from four (4) years not updated.
